
DOCKERFILE := Dockerfile
PROJECT := ignition
ORIGIN := $(shell git remote get-url origin | sed -e 's/^.*@//g')
REVISION := $(shell git rev-parse --short HEAD)
DOCKERFILES := $(sort $(wildcard */$(DOCKERFILE)))
USERNAME := naokitakahashi12

# Directory identities
BUILD_ENV := buildenv
BLUEPRINT := blueprint
CITADEL := citadel
DOME := dome

# Image type
BINALY := binary
BINALY_CUDAGL_102 := $(BINALY)-with-cudagl-10.2
BINALY_CUDAGL_92 := $(BINALY)-with-cudagl-9.2
DEVEL := devel
DEVEL_CUDAGL_102 := $(DEVEL)-with-cudagl-10.2
DEVEL_CUDAGL_92 := $(DEVEL)-with-cudagl-9.2

# Support ubuntu distributions
BIONIC := bionic
FOCAL := focal

# Build image tag name
BINARY_FOCAL_CITADEL_TAG := $(CITADEL)-$(FOCAL)
BINARY_BIONIC_DOME_TAG := $(DOME)-$(BIONIC)
BINARY_BIONIC_CITADEL_TAG := $(CITADEL)-$(BIONIC)
BINARY_BIONIC_BLUEPRINT_TAG := $(BLUEPRINT)-$(BIONIC)
BINARY_CUDAGL_102_BIONIC_DOME_TAG := $(DOME)-cudagl-10.2-$(BIONIC)
BINARY_CUDAGL_92_BIONIC_DOME_TAG := $(DOME)-cudagl-9.2-$(BIONIC)
BINARY_CUDAGL_102_BIONIC_CITADEL_TAG := $(CITADEL)-cudagl-10.2-$(BIONIC)
BINARY_CUDAGL_92_BIONIC_CITADEL_TAG := $(CITADEL)-cudagl-9.2-$(BIONIC)
BINARY_CUDAGL_102_BIONIC_BLUEPRINT_TAG := $(BLUEPRINT)-cudagl-10.2-$(BIONIC)
BINARY_CUDAGL_92_BIONIC_BLUEPRINT_TAG := $(BLUEPRINT)-cudagl-9.2-$(BIONIC)
DEVEL_BIONIC_DOME_TAG := $(DOME)-$(DEVEL)-$(BIONIC)
DEVEL_BIONIC_CITADEL_TAG := $(CITADEL)-$(DEVEL)-$(BIONIC)
DEVEL_BIONIC_BLUEPRINT_TAG := $(BLUEPRINT)-$(DEVEL)-$(BIONIC)
DEVEL_BIONIC_BUILD_ENV_TAG := $(BUILD_ENV)-$(BIONIC)
DEVEL_CUDAGL_102_BIONIC_DOME_TAG := $(DOME)-$(DEVEL)-cudagl-10.2-$(BIONIC)
DEVEL_CUDAGL_102_BIONIC_CITADEL_TAG := $(CITADEL)-$(DEVEL)-cudagl-10.2-$(BIONIC)
DEVEL_CUDAGL_102_BIONIC_BLUEPRINT_TAG := $(BLUEPRINT)-$(DEVEL)-cudagl-10.2-$(BIONIC)
DEVEL_CUDAGL_102_BIONIC_BUILD_ENV_TAG := $(BUILD_ENV)-cudagl-10.2-$(BIONIC)
DEVEL_CUDAGL_92_BIONIC_DOME_TAG := $(DOME)-$(DEVEL)-cudagl-9.2-$(BIONIC)
DEVEL_CUDAGL_92_BIONIC_CITADEL_TAG := $(CITADEL)-$(DEVEL)-cudagl-9.2-$(BIONIC)
DEVEL_CUDAGL_92_BIONIC_BLUEPRINT_TAG := $(BLUEPRINT)-$(DEVEL)-cudagl-9.2-$(BIONIC)
DEVEL_CUDAGL_92_BIONIC_BUILD_ENV_TAG := $(BUILD_ENV)-cudagl-9.2-$(BIONIC)

define dockerbuild
	@docker build \
		--file $1 \
		--build-arg GIT_REVISION=$(REVISION) \
		--build-arg GIT_ORIGIN=$(ORIGIN) \
		--tag $2 \
	.
endef

.PHONY: all
all: help

.PHONY: build
build: \
	$(BINARY_FOCAL_CITADEL_TAG) \
	$(BINARY_BIONIC_DOME_TAG) \
	$(BINARY_BIONIC_CITADEL_TAG) \
	$(BINARY_BIONIC_BLUEPRINT_TAG) \
	$(BINARY_CUDAGL_102_BIONIC_DOME_TAG) \
	$(BINARY_CUDAGL_92_BIONIC_DOME_TAG) \
	$(BINARY_CUDAGL_102_BIONIC_CITADEL_TAG) \
	$(BINARY_CUDAGL_92_BIONIC_CITADEL_TAG) \
	$(BINARY_CUDAGL_102_BIONIC_BLUEPRINT_TAG) \
	$(BINARY_CUDAGL_92_BIONIC_BLUEPRINT_TAG) \
	$(DEVEL_BIONIC_DOME_TAG) \
	$(DEVEL_BIONIC_CITADEL_TAG) \
	$(DEVEL_BIONIC_BLUEPRINT_TAG) \
	$(DEVEL_CUDAGL_102_BIONIC_DOME_TAG) \
	$(DEVEL_CUDAGL_102_BIONIC_CITADEL_TAG) \
	$(DEVEL_CUDAGL_102_BIONIC_BLUEPRINT_TAG) \
	$(DEVEL_CUDAGL_92_BIONIC_DOME_TAG) \
	$(DEVEL_CUDAGL_92_BIONIC_CITADEL_TAG) \
	$(DEVEL_CUDAGL_92_BIONIC_BLUEPRINT_TAG) \

$(BINARY_FOCAL_CITADEL_TAG): $(BINALY)/$(FOCAL)/$(CITADEL)/$(DOCKERFILE)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(BINARY_BIONIC_DOME_TAG): $(BINALY)/$(BIONIC)/$(DOME)/$(DOCKERFILE)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(BINARY_BIONIC_CITADEL_TAG): $(BINALY)/$(BIONIC)/$(CITADEL)/$(DOCKERFILE)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(BINARY_BIONIC_BLUEPRINT_TAG): $(BINALY)/$(BIONIC)/$(BLUEPRINT)/$(DOCKERFILE)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(BINARY_CUDAGL_102_BIONIC_DOME_TAG): $(BINALY_CUDAGL_102)/$(BIONIC)/$(DOME)/$(DOCKERFILE)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(BINARY_CUDAGL_92_BIONIC_DOME_TAG): $(BINALY_CUDAGL_92)/$(BIONIC)/$(DOME)/$(DOCKERFILE)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(BINARY_CUDAGL_102_BIONIC_CITADEL_TAG): $(BINALY_CUDAGL_102)/$(BIONIC)/$(CITADEL)/$(DOCKERFILE)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(BINARY_CUDAGL_92_BIONIC_CITADEL_TAG): $(BINALY_CUDAGL_92)/$(BIONIC)/$(CITADEL)/$(DOCKERFILE)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(BINARY_CUDAGL_102_BIONIC_BLUEPRINT_TAG): $(BINALY_CUDAGL_102)/$(BIONIC)/$(BLUEPRINT)/$(DOCKERFILE)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(BINARY_CUDAGL_92_BIONIC_BLUEPRINT_TAG): $(BINALY_CUDAGL_92)/$(BIONIC)/$(BLUEPRINT)/$(DOCKERFILE)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(DEVEL_BIONIC_DOME_TAG): $(DEVEL)/$(BIONIC)/$(DOME)/$(DOCKERFILE) $(DEVEL_BIONIC_BUILD_ENV_TAG)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(DEVEL_BIONIC_CITADEL_TAG): $(DEVEL)/$(BIONIC)/$(CITADEL)/$(DOCKERFILE) $(DEVEL_BIONIC_BUILD_ENV_TAG)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(DEVEL_BIONIC_BLUEPRINT_TAG): $(DEVEL)/$(BIONIC)/$(BLUEPRINT)/$(DOCKERFILE) $(DEVEL_BIONIC_BUILD_ENV_TAG)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(DEVEL_BIONIC_BUILD_ENV_TAG): $(DEVEL)/$(BIONIC)/$(BUILD_ENV)/$(DOCKERFILE)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(DEVEL_CUDAGL_102_BIONIC_DOME_TAG): $(DEVEL_CUDAGL_102)/$(BIONIC)/$(DOME)/$(DOCKERFILE) $(DEVEL_CUDAGL_102_BIONIC_BUILD_ENV_TAG)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(DEVEL_CUDAGL_102_BIONIC_CITADEL_TAG): $(DEVEL_CUDAGL_102)/$(BIONIC)/$(CITADEL)/$(DOCKERFILE) $(DEVEL_CUDAGL_102_BIONIC_BUILD_ENV_TAG)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(DEVEL_CUDAGL_102_BIONIC_BLUEPRINT_TAG): $(DEVEL_CUDAGL_102)/$(BIONIC)/$(BLUEPRINT)/$(DOCKERFILE) $(DEVEL_CUDAGL_102_BIONIC_BUILD_ENV_TAG)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(DEVEL_CUDAGL_102_BIONIC_BUILD_ENV_TAG): $(DEVEL_CUDAGL_102)/$(BIONIC)/$(BUILD_ENV)/$(DOCKERFILE)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(DEVEL_CUDAGL_92_BIONIC_DOME_TAG): $(DEVEL_CUDAGL_92)/$(BIONIC)/$(DOME)/$(DOCKERFILE) $(DEVEL_CUDAGL_92_BIONIC_BUILD_ENV_TAG)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(DEVEL_CUDAGL_92_BIONIC_CITADEL_TAG): $(DEVEL_CUDAGL_92)/$(BIONIC)/$(CITADEL)/$(DOCKERFILE) $(DEVEL_CUDAGL_92_BIONIC_BUILD_ENV_TAG)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(DEVEL_CUDAGL_92_BIONIC_BLUEPRINT_TAG): $(DEVEL_CUDAGL_92)/$(BIONIC)/$(BLUEPRINT)/$(DOCKERFILE) $(DEVEL_CUDAGL_92_BIONIC_BUILD_ENV_TAG)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

$(DEVEL_CUDAGL_92_BIONIC_BUILD_ENV_TAG): $(DEVEL_CUDAGL_92)/$(BIONIC)/$(BUILD_ENV)/$(DOCKERFILE)
	$(eval DOCKERIMAGE := "$(USERNAME)/$(PROJECT):$@")
	$(call dockerbuild, $<, $(DOCKERIMAGE))

.PHONY: clean
clean:
	@docker image rm $(USERNAME)/$(PROJECT):$(BINARY_FOCAL_CITADEL_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(BINARY_BIONIC_DOME_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(BINARY_BIONIC_CITADEL_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(BINARY_BIONIC_BLUEPRINT_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(BINARY_CUDAGL_102_BIONIC_DOME_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(BINARY_CUDAGL_102_BIONIC_CITADEL_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(BINARY_CUDAGL_102_BIONIC_BLUEPRINT_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(BINARY_CUDAGL_92_BIONIC_DOME_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(BINARY_CUDAGL_92_BIONIC_CITADEL_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(BINARY_CUDAGL_92_BIONIC_BLUEPRINT_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(DEVEL_BIONIC_DOME_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(DEVEL_BIONIC_CITADEL_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(DEVEL_BIONIC_BLUEPRINT_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(DEVEL_BIONIC_BUILD_ENV_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_102_BIONIC_DOME_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_102_BIONIC_CITADEL_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_102_BIONIC_BLUEPRINT_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_102_BIONIC_BUILD_ENV_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_92_BIONIC_DOME_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_92_BIONIC_CITADEL_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_92_BIONIC_BLUEPRINT_TAG)
	@docker image rm $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_92_BIONIC_BUILD_ENV_TAG)

.PHONY: pull
pull:
	@docker pull $(USERNAME)/$(PROJECT):$(BINARY_FOCAL_CITADEL_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(BINARY_BIONIC_DOME_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(BINARY_BIONIC_CITADEL_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(BINARY_BIONIC_BLUEPRINT_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(BINARY_CUDAGL_102_BIONIC_DOME_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(BINARY_CUDAGL_102_BIONIC_CITADEL_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(BINARY_CUDAGL_102_BIONIC_BLUEPRINT_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(BINARY_CUDAGL_92_BIONIC_DOME_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(BINARY_CUDAGL_92_BIONIC_CITADEL_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(BINARY_CUDAGL_92_BIONIC_BLUEPRINT_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(DEVEL_BIONIC_DOME_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(DEVEL_BIONIC_CITADEL_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(DEVEL_BIONIC_BLUEPRINT_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(DEVEL_BIONIC_BUILD_ENV_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_102_BIONIC_DOME_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_102_BIONIC_CITADEL_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_102_BIONIC_BLUEPRINT_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_102_BIONIC_BUILD_ENV_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_92_BIONIC_DOME_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_92_BIONIC_CITADEL_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_92_BIONIC_BLUEPRINT_TAG)
	@docker pull $(USERNAME)/$(PROJECT):$(DEVEL_CUDAGL_92_BIONIC_BUILD_ENV_TAG)

.PHONY: help
help:
	@echo ""
	@echo " make <command> [option]"
	@echo ""
	@echo " Support commands"
	@echo " help  : print support commands"
	@echo " build : building docker images"
	@echo " clean : clean docker images"
	@echo " pull  : pulling docker images from registry"
	@echo ""
	@echo " Options"
	@echo " See the 'make --help'"
	@echo ""

